### 全局开发环境配置文件 ###

spring:
  data:
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis服务器连接端口（默认为6379）
      password: pwd@123QWE # Redis服务器连接密码
      database: 1  # Redis数据库索引（默认为0）
      timeout: 10000ms # 连接超时时间（毫秒）
      lettuce:
        pool:
          enabled: true # 是否启用连接池
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制，默认为8）
          max-wait: 10000ms # 连接池最大阻塞等待时间（使用负值表示没有限制，默认为-1ms）
          max-idle: 4 # 连接池中的最大空闲连接（使用负值表示没有限制，默认为8）
          min-idle: 1 # 连接池中的最小空闲连接（默认为0）

# sa-token
sa-token:
  token-name: satoken # token名称（同时也是cookie名称）
  timeout: 2592000 # token有效期（单位：秒） 默认2592000（30天），-1代表永久有效
  active-timeout: -1 # token最低活跃频率（单位：秒），如果token超过此时间没有访问系统就会被冻结，默认-1代表不限制，永不冻结
  is-concurrent: true # 是否允许同一账号多地同时登录（为true时允许一起登录,为false时新登录挤掉旧登录）
  is-share: false # 在多人登录同一账号时，是否共用一个token（为true时所有登录共用一个token, 为false时每次登录新建一个token）
  token-style: uuid # token风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  is-log: true # 是否输出操作日志
