### 全局开发环境配置文件 ###

spring:
  data:
    # 配置业务使用的 Redis 连接
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis服务器连接端口（默认为6379）
      password: pwd@123QWE # Redis服务器连接密码
      database: 1  # Redis数据库索引（默认为0）
      timeout: 10000ms # 连接超时时间（毫秒）
      lettuce:
        pool:
          enabled: true # 是否启用连接池
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制，默认为8）
          max-wait: 10000ms # 连接池最大阻塞等待时间（使用负值表示没有限制，默认为-1ms）
          max-idle: 4 # 连接池中的最大空闲连接（使用负值表示没有限制，默认为8）
          min-idle: 1 # 连接池中的最小空闲连接（默认为0）

# sa-token
sa-token:
  sso-client: # SSO-相关配置
    client: sso-client1 # client 标识
    server-url: http://sso.stp.com:9100 # SSO-Server端主机地址
  # 配置 Sa-Token 单独使用的Redis连接（此处需要和 SSO-Server 端连接同一个 Redis）
  # 注：使用 alone-redis 需要在 pom.xml 引入 sa-token-alone-redis 依赖
  alone-redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口（默认为6379）
    password: pwd@123QWE # Redis服务器连接密码
    database: 2  # Redis数据库索引（默认为0）
    timeout: 10000ms # 连接超时时间（毫秒）
    lettuce:
      pool:
        enabled: true # 是否启用连接池
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制，默认为8）
        max-wait: 10000ms # 连接池最大阻塞等待时间（使用负值表示没有限制，默认为-1ms）
        max-idle: 4 # 连接池中的最大空闲连接（使用负值表示没有限制，默认为8）
        min-idle: 1 # 连接池中的最小空闲连接（默认为0）