### 全局生产环境配置文件 ###

spring:
  data:
    # 配置业务使用的 Redis 连接
    redis:
      host: 192.168.0.10 # Redis服务器地址
      port: 6379 # Redis服务器连接端口（默认为6379）
      password: pwd@123QWE # Redis服务器连接密码
      database: 5  # Redis数据库索引（默认为0）
      timeout: 10000ms # 连接超时时间（毫秒）
      lettuce:
        pool:
          enabled: true # 是否启用连接池
          max-active: 128 # 连接池最大连接数（使用负值表示没有限制，默认为8）
          max-wait: 10000ms # 连接池最大阻塞等待时间（使用负值表示没有限制，默认为-1ms）
          max-idle: 8 # 连接池中的最大空闲连接（使用负值表示没有限制，默认为8）
          min-idle: 4 # 连接池中的最小空闲连接（默认为0）

# sa-token
sa-token:
  is-log: true # 打印操作日志
  sso-client: # SSO-相关配置
    client: sso-client3 # 应用标识
    server-url: http://sa-sso-server.com:9400 # SSO-Server 端主机地址
    is-http: true # 使用 Http 请求校验 ticket (模式三)
    secret-key: SSO-C3-kQwIOrYvnXmSDkwEiFngrKidMcdrgKor # API 接口调用秘钥